### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Rohit Mishra",
  "email": "rohit@gmal.com",
  "address": "123 main street",
  "dateOfBirth": "2005-02-03",
  "registeredDate": "2026-01-07"
}

###